import React, { useState } from 'react';
import { AnalysisResult, SupportedLanguage } from '../types';
import { X, Copy, Check, Printer, Share2, Scale, MessageSquare } from 'lucide-react';

interface ExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  analysis: AnalysisResult;
  selectedLanguage: SupportedLanguage;
}

export const ExportModal: React.FC<ExportModalProps> = ({
  isOpen,
  onClose,
  analysis,
  selectedLanguage
}) => {
  const [copied, setCopied] = useState<boolean>(false);

  if (!isOpen) return null;

  const plainText = analysis.plainLanguageExplanations[selectedLanguage] || analysis.plainLanguageExplanations['hi'];

  const formattedShareMessage = `⚖️ *NYAYASCRIBE COURT ORDER SUMMARY*
📋 *Case:* ${analysis.title} (${analysis.caseNumber})
🏛️ *Court:* ${analysis.courtName}
📅 *Order Date:* ${analysis.orderDate}

📌 *OPERATIVE COURT DIRECTION (Verbatim):*
"${analysis.operativeDirectionVerbatim || 'Refused / See Document'}"

💡 *PLAIN LANGUAGE EXPLANATION:*
${plainText}

✅ *NEXT STEPS FOR LITIGANT:*
${analysis.nextSteps.map((s, i) => `${i + 1}. ${s.action}\n   ⏰ Deadline: ${s.deadline}\n   🏛️ Forum: ${s.forum}`).join('\n\n')}

⚠️ *DISCLAIMER:* This summary is generated by NyayVaani Document Intelligence for literacy assistance. Please verify with your advocate or court clerk before taking legal action.`;

  const copyToClipboard = () => {
    navigator.clipboard.writeText(formattedShareMessage);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="fixed inset-0 z-50 bg-slate-900/60 backdrop-blur-xs flex items-center justify-center p-4 overflow-y-auto">
      <div className="bg-white border border-slate-200 rounded-2xl w-full max-w-2xl shadow-xl overflow-hidden text-slate-900 my-8">
        
        {/* Header */}
        <div className="px-6 py-4 border-b border-slate-200 flex items-center justify-between bg-slate-50">
          <div className="flex items-center gap-2">
            <Share2 className="h-5 w-5 text-indigo-600" />
            <h2 className="text-base font-bold text-slate-900">Share / Print Litigant Summary Sheet</h2>
          </div>
          <button onClick={onClose} className="text-slate-400 hover:text-slate-700 p-1 rounded-lg cursor-pointer">
            <X className="h-5 w-5" />
          </button>
        </div>

        {/* Content Preview */}
        <div className="p-6 space-y-4">
          <p className="text-xs text-slate-500">
            Copy this formatted message for WhatsApp / Telegram or print as a physical one-sheet for the litigant.
          </p>

          <div className="p-4 bg-slate-50 border border-slate-200 rounded-xl font-mono text-xs text-slate-800 leading-relaxed max-h-80 overflow-y-auto whitespace-pre-wrap select-all">
            {formattedShareMessage}
          </div>
        </div>

        {/* Actions */}
        <div className="px-6 py-4 bg-slate-50 border-t border-slate-200 flex items-center justify-between">
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-white hover:bg-slate-100 text-slate-700 text-xs font-semibold rounded-lg flex items-center gap-1.5 transition-colors cursor-pointer border border-slate-300 shadow-xs"
          >
            <Printer className="h-4 w-4" />
            <span>Print One-Sheet</span>
          </button>

          <button
            onClick={copyToClipboard}
            className="px-5 py-2 bg-indigo-600 hover:bg-indigo-700 text-white font-semibold text-xs rounded-xl flex items-center gap-2 shadow-xs transition-all cursor-pointer"
          >
            {copied ? (
              <>
                <Check className="h-4 w-4 text-white" />
                <span>Copied to Clipboard!</span>
              </>
            ) : (
              <>
                <Copy className="h-4 w-4" />
                <span>Copy for WhatsApp / Telegram</span>
              </>
            )}
          </button>
        </div>

      </div>
    </div>
  );
};
